config/routes.rb
Rails.application.routes.draw do

  resources :recipes do
    resources :recipe_ingredients, only: [:new, :create, :destroy]
  end
  resources :ingredients
  resources :menus

end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :starter, class_name: 'Recipe', optional: true
  belongs_to :main, class_name: 'Recipe'
  belongs_to :dessert, class_name: 'Recipe', optional: true

  validates :main, uniqueness: { scope: %i[starter dessert], message: "this menu composition already been existed" }

  # instance method : to get all the ingredients for a menu
  def ingredients
    ingredients = main.ingredients
    ingredients += starter.ingredients if starter.present?
    ingredients += dessert.ingredients if dessert.present?

    ingredients
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: %i[edit update destroy]
  before_action :set_recipes, only: %i[new create edit update]

  def index
    @menus = Menu.all.order(:main_id)
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)

    if @menu.save
      redirect_to menus_path, notice: 'Menu was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @menu.destroy

    redirect_to menus_path, notice: 'Menu was successfully destroyed.'
  end

  private

  def menu_params
    params.require(:menu).permit(:starter_id, :main_id, :dessert_id)
  end

  def set_menu
    @menu = Menu.find(params[:id])
  end

  def set_recipes
    @starters = Recipe.starter.all.order(:name)
    @mains = Recipe.main.all.order(:name)
    @desserts = Recipe.dessert.all.order(:name)
  end
end

app/views/menus/_form.html.erb
<%= form_for(menu, local: true) do |form| %>
  <% if menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :starter_id %>
    <%= form.select :starter_id, @starters.map { |starter| [starter.name, starter.id]}, prompt: 'Select a starter or not' %>
  </div>

  <div class="field">
    <%= form.label :main_id %>
    <%= form.select :main_id, @mains.map { |main| [main.name, main.id]} %>
  </div>

  <div class="field">
    <%= form.label :dessert_id %>
    <%= form.select :dessert_id, @desserts.map { |dessert| [dessert.name, dessert.id]}, prompt: 'Select a dessert or not' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Menus</h1>

<%= table do %>
  <%= thead html_class: "test" do %>
    <tr>
      <th>N°</th>
      <th>Entrée</th>
      <th>Plat</th>
      <th>Dessert</th>
      <th>Ingredients</th>
      <th colspan="3"></th>
    </tr>
  <% end %>

  <%= tbody do %>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.id %></td>
        <td><%= menu.starter.name if menu.starter.present? %></td>
        <td><%= menu.main.name if menu.main.present? %></td>
        <td><%= menu.dessert.name if menu.dessert.present? %></td>
        <td>
          <% menu.ingredients.each do |ingredient| %>
            <%= ingredient.name %><br/>
          <% end %>
        </td>
        <td><%= link_to 'Show', menu %></td>
        <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  <% end %>
<% end %>

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Back', menus_path %>