config/routes.rb
Rails.application.routes.draw do

  resources :recipes do
    resources :recipe_ingredients, only: [:new, :create, :destroy]
  end
  resources :ingredients
  resources :menus

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  ########## CONSTANTS ########
  CATEGORIES = %w[Entrée Plat Dessert].freeze
  DIFFICULTIES = [
    ['Non défini', 0],
    ['Très Facile', 1],
    ['Facile', 2],
    ['Moyen', 3],
    ['Difficile', 4],
    ['Très Difficile', 5]
  ].freeze

  ########## ASSOCIATIONS ########
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :starter_menus, class_name: 'Menu', foreign_key: 'starter_id'
  has_many :main_menus, class_name: 'Menu', foreign_key: 'main_id'
  has_many :dessert_menus, class_name: 'Menu', foreign_key: 'dessert_id'

  ########## VALIDATIONS ##########
  validates :name, presence: true, uniqueness: true
  validates :prep_time, :cooking_time, numericality: { greater_than_or_equal: 0 }

  ########## SCOPES ##########
  scope :starter, -> { where(categorie: 'Entrée') }
  scope :main, -> { where(categorie: 'Plat') }
  scope :dessert, -> { where(categorie: 'Dessert') }

  ########## INSTANCES METHODS ########
  def difficulty_to_human
    DIFFICULTIES[difficulty][0]
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :set_ingredients, only: [:new, :edit]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update

    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def set_ingredients
      @ingredients = Ingredient.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :description, :categorie, :difficulty, :prep_time, :cooking_time, ingredients: [])
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :categorie %>
    <%= form.select :categorie, Recipe::CATEGORIES %>
  </div>

  <div class="field">
    <%= form.label :difficulty %>
    <%= form.select :difficulty, Recipe::DIFFICULTIES %>
  </div>

  <div class="field">
    <%= form.label :prep_time %>
    <%= form.number_field :prep_time %>
  </div>

  <div class="field">
    <%= form.label :cooking_time %>
    <%= form.number_field :cooking_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Categorie</th>
      <th>Difficulty</th>
      <th>Prep time (min)</th>
      <th>Cooking time (min)</th>
      <th>Liste des ingrédients</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= recipe.description %></td>
        <td><%= recipe.categorie %></td>
        <td><%= recipe.difficulty_to_human %></td>
        <td><%= recipe.prep_time %></td>
        <td><%= recipe.cooking_time %></td>
        <td>
          <% recipe.ingredients.each do |ingredient| %>
            <%= ingredient.name %><br/>
          <% end %>
        </td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Add an Ingredient',new_recipe_recipe_ingredient_path(recipe) %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<p>
  <strong>Categorie:</strong>
  <%= @recipe.categorie %>
</p>

<p>
  <strong>Difficulty:</strong>
  <%= @recipe.difficulty_to_human %>
</p>

<p>
  <strong>Prep time:</strong>
  <%= pluralize(@recipe.prep_time, 'minute', plural: 'minutes') %>
</p>

<p>
  <strong>Cooking time:</strong>
  <%= pluralize(@recipe.cooking_time, 'minute', plural: 'minutes') %>
</p>

<p>
  <strong>Ingredients:</strong>
  <% @recipe.recipe_ingredients.each do |recipe_ingredient| %>
    <%= recipe_ingredient.ingredient.name %> <%= link_to 'remove', recipe_recipe_ingredient_path(@recipe, recipe_ingredient), method: :delete, data: { confirm: 'Are you sure?' } %> /
  <% end %>
</p>


<%= link_to 'Add an Ingredient', new_recipe_recipe_ingredient_path(@recipe) %>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>