config/routes.rb
Rails.application.routes.draw do

  resources :recipes do
    resources :recipe_ingredients, only: [:new, :create, :destroy]
  end
  resources :ingredients
  resources :menus

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients

  validates :name, presence: true, uniqueness: true
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]
  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name)
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper

  def my_div(html_class: "", &block)
    content_tag(:div, class: "m-2 #{html_class}") do
      # capture the value of the block a string
      capture(&block)
    end
  end

  # TABLE
  def table(html_class: "", &block)
    content_tag(:div, class: "table-responsible") do
      content_tag(:table, class: "table #{html_class}") do
        # capture the value of the block a string
        capture(&block)
      end
    end
  end

  def thead(html_class: "", &block)
    content_tag(:thead, class: "table #{html_class}", style: "background: grey") do
      # capture the value of the block a string
      capture(&block)
    end
  end

  def tbody(html_class: "", &block)
    content_tag(:tbody, class: "table #{html_class}") do
      # capture the value of the block a string
      capture(&block)
    end
  end

  # LIST
  def map_join(objects, &block)
    safe_join(objects.map(&block))
  end

  def list(html_class: "", elements: [], &block)
    if elements.none?
      content_tag(:p, "none")
    else
      content_tag(:div, class: "wrapper") do
        map_join(elements) do |element|
          content_tag(:div, class: "test") do
            element
          end
        end
      end
    end
  end
end

app/views/ingredients/_form.html.erb
<%= form_for(ingredient, local: true) do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingredients</h1>

<%= table do %>
  <%= thead do %>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  <% end %>

  <%= tbody do %>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  <% end %>
<% end %>

<%= link_to 'New Ingredient', new_ingredient_path %>

<%= my_div(html_class: "test") do %>
  <p>Un</p>
  <p>Deux</p>
  <p>Trois</p>
<% end %>

<%= list(elements: ["un", "deux", "trois"]) %>

<%= list %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>